#!/bin/bash
# setup.sh — One-command P2P bot setup wizard
# Run: bash setup.sh

set -e

echo ""
echo "╔═══════════════════════════════════════╗"
echo "║     P2P Escrow Bot -- Setup Wizard    ║"
echo "╚═══════════════════════════════════════╝"
echo ""

# ── Dependency checks ──────────────────────────────────────────────────────────

if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker not found. Install Docker first: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "ERROR: Docker Compose not found. Install Docker Desktop or 'docker-compose-plugin'."
    exit 1
fi

echo "OK: Docker $(docker --version | awk '{print $3}' | tr -d ',')"
echo "OK: Docker Compose $(docker compose version --short)"
echo ""

# ── Collect required values ────────────────────────────────────────────────────

echo "Step 1/4: Telegram Bot Token"
echo "   Get it from @BotFather -> /newbot"
read -rp "   BOT_TOKEN: " BOT_TOKEN
if [ -z "$BOT_TOKEN" ]; then
    echo "ERROR: BOT_TOKEN cannot be empty"
    exit 1
fi

echo ""
echo "Step 2/4: Crypto Pay Token"
echo "   Get it from @CryptoBot -> Crypto Pay -> My Apps -> Create App"
read -rp "   CRYPTOPAY_TOKEN: " CRYPTOPAY_TOKEN
if [ -z "$CRYPTOPAY_TOKEN" ]; then
    echo "ERROR: CRYPTOPAY_TOKEN cannot be empty"
    exit 1
fi

echo ""
echo "Step 3/4: Admin Telegram IDs"
echo "   Get your ID from @userinfobot (comma-separated for multiple admins)"
read -rp "   ADMIN_IDS: " ADMIN_IDS
if [ -z "$ADMIN_IDS" ]; then
    echo "ERROR: ADMIN_IDS cannot be empty"
    exit 1
fi

echo ""
echo "Step 4/4: Gemini API Key (optional -- for AI dispute mediation)"
echo "   Get it from https://aistudio.google.com/app/apikey"
read -rp "   GEMINI_API_KEY (press Enter to skip): " GEMINI_API_KEY

# ── Generate secrets ───────────────────────────────────────────────────────────

echo ""
echo "Generating cryptographic secrets..."

CRYPTOPAY_CALLBACK_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
AES_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(16))")

# ── Write .env ─────────────────────────────────────────────────────────────────

# Backup existing .env if present
if [ -f .env ]; then
    cp .env ".env.backup.$(date +%Y%m%d_%H%M%S)"
    echo "INFO: Existing .env backed up"
fi

cat > .env << EOF
# Generated by setup.sh on $(date)
# WARNING: Never commit this file to git.

# ── Telegram ───────────────────────────────────────────────────────────────────
BOT_TOKEN=${BOT_TOKEN}

# ── Crypto Pay ─────────────────────────────────────────────────────────────────
CRYPTOPAY_TOKEN=${CRYPTOPAY_TOKEN}
CRYPTOPAY_CALLBACK_SECRET=${CRYPTOPAY_CALLBACK_SECRET}

# ── Database ───────────────────────────────────────────────────────────────────
POSTGRES_URI=postgresql+asyncpg://p2pbot:${POSTGRES_PASSWORD}@postgres:5432/p2pbot
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── Encryption ─────────────────────────────────────────────────────────────────
# CRITICAL: Do NOT change AES_KEY after first run.
# All encrypted wallet keys in the DB will become unreadable.
AES_KEY=${AES_KEY}

# ── Admins ─────────────────────────────────────────────────────────────────────
ADMIN_IDS=${ADMIN_IDS}

# ── AI Mediator (optional) ─────────────────────────────────────────────────────
GEMINI_API_KEY=${GEMINI_API_KEY}

# ── Order settings ─────────────────────────────────────────────────────────────
# Fine-tune these in branding.yaml instead
ORDER_TIMEOUT_SEC=1800
ORDER_MIN_AMOUNT_USDT=1.0
ORDER_MAX_AMOUNT_USDT=50000.0
EOF

echo "OK: .env created"

# ── Copy branding template ─────────────────────────────────────────────────────

if [ ! -f branding.yaml ]; then
    if [ -f branding.yaml.example ]; then
        cp branding.yaml.example branding.yaml
        echo "OK: branding.yaml created from template"
    else
        echo "WARNING: branding.yaml.example not found, skipping branding copy"
    fi
else
    echo "INFO: branding.yaml already exists, keeping it"
fi

# ── Done ───────────────────────────────────────────────────────────────────────

echo ""
echo "╔═══════════════════════════════════════╗"
echo "║         Setup Complete!               ║"
echo "╚═══════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Edit branding.yaml with your bot name, fees, and payment methods"
echo "  2. Run:  docker compose up -d --build"
echo "  3. Logs: docker compose logs -f bot"
echo ""
echo "WARNING: Keep .env secret. Never commit it to git."
