"""Models for Marketplace products and deals (TMA integration)."""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from db.models.user import User

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.models.base import Base
from db.models.wallet import WalletChain


class CurrencyType(enum.StrEnum):
    """Supported currencies for marketplace products."""

    XTR = "XTR"  # Telegram Stars
    FIAT = "FIAT"  # Fiat via Escrow
    CRYPTO = "CRYPTO"  # Crypto via Escrow


class DealStatus(enum.StrEnum):
    """Lifecycle states for a marketplace deal."""

    created = "created"  # Deal initiated, awaiting payment
    paid = "paid"  # Payment confirmed (or Stars paid)
    delivered = "delivered"  # Seller marked as delivered / Digital good auto-delivered
    completed = "completed"  # Buyer confirmed receipt
    dispute = "dispute"  # Opened dispute
    cancelled = "cancelled"  # Cancelled by buyer or timeout


class DiscountType(enum.StrEnum):
    """Type of discount for promo codes."""

    percentage = "percentage"
    fixed = "fixed"


class PromoCode(Base):
    """Promo codes generated by sellers for discounts."""

    __tablename__ = "promo_codes"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    seller_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id", ondelete="CASCADE"), nullable=False, index=True
    )
    code: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    discount_type: Mapped[DiscountType] = mapped_column(
        Enum(DiscountType, name="promo_discount_type"), nullable=False
    )
    discount_value: Mapped[Decimal] = mapped_column(Numeric(precision=18, scale=2), nullable=False)

    max_uses: Mapped[int | None] = mapped_column(nullable=True)
    current_uses: Mapped[int] = mapped_column(default=0, nullable=False)

    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class Product(Base):
    """Marketplace product created by a seller."""

    __tablename__ = "products"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    seller_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id", ondelete="CASCADE"), nullable=False, index=True
    )
    seller: Mapped[User] = relationship("User")

    title: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    is_digital: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    digital_content: Mapped[str] = mapped_column(
        Text, nullable=True
    )  # Secret link/key for digital goods
    image_urls: Mapped[list[str]] = mapped_column(JSONB, server_default="[]", nullable=False)

    # Pricing
    price: Mapped[Decimal] = mapped_column(Numeric(precision=18, scale=2), nullable=False)
    currency_type: Mapped[CurrencyType] = mapped_column(
        Enum(CurrencyType, name="product_currency_type"), nullable=False
    )
    fiat_currency: Mapped[str] = mapped_column(String(10), nullable=True)  # E.g. RUB, USD if FIAT
    crypto_asset: Mapped[str] = mapped_column(String(10), nullable=True)  # E.g. TON, USDT if CRYPTO
    crypto_chain: Mapped[WalletChain] = mapped_column(
        Enum(WalletChain, name="wallet_chain", create_type=False), nullable=True
    )
    crypto_network: Mapped[str] = mapped_column(String(20), nullable=True)  # E.g. mainnet, testnet

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    is_promoted: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false", nullable=False
    )
    promoted_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    deals: Mapped[list[MarketplaceDeal]] = relationship("MarketplaceDeal", back_populates="product")


class MarketplaceDeal(Base):
    """A transaction/deal between a buyer and a seller for a Product."""

    __tablename__ = "marketplace_deals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    product_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    buyer_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id", ondelete="RESTRICT"), nullable=False, index=True
    )
    seller_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id", ondelete="RESTRICT"), nullable=False, index=True
    )

    status: Mapped[DealStatus] = mapped_column(
        Enum(DealStatus, name="deal_status"), nullable=False, default=DealStatus.created, index=True
    )

    amount: Mapped[Decimal] = mapped_column(Numeric(precision=18, scale=2), nullable=False)
    original_amount: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=18, scale=2), nullable=True
    )
    currency_type: Mapped[CurrencyType] = mapped_column(
        Enum(CurrencyType, name="deal_currency_type"), nullable=False
    )
    promo_code_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("promo_codes.id", ondelete="SET NULL"), nullable=True
    )

    # Telegram Stars Specific
    provider_payment_charge_id: Mapped[str] = mapped_column(String(255), nullable=True)
    telegram_payment_charge_id: Mapped[str] = mapped_column(String(255), nullable=True)

    # On-Chain Escrow (Phase 8)
    blockchain: Mapped[WalletChain] = mapped_column(
        Enum(WalletChain, name="wallet_chain", create_type=False), nullable=True
    )
    network: Mapped[str] = mapped_column(String(20), nullable=True)
    escrow_wallet_address: Mapped[str] = mapped_column(String(256), nullable=True)
    escrow_wallet_private_key_enc: Mapped[str] = mapped_column(String(1024), nullable=True)
    buyer_wallet_address: Mapped[str] = mapped_column(String(256), nullable=True)
    tx_hash_deposit: Mapped[str] = mapped_column(String(256), nullable=True)
    tx_hash_release: Mapped[str] = mapped_column(String(256), nullable=True)

    # Dispute tracking (Phase 10)
    dispute_reason: Mapped[str] = mapped_column(Text, nullable=True)
    dispute_opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    dispute_resolved_by: Mapped[int] = mapped_column(BigInteger, nullable=True)  # admin tg_id
    dispute_resolution: Mapped[str] = mapped_column(String(32), nullable=True)  # buyer|seller
    dispute_resolution_comment: Mapped[str] = mapped_column(Text, nullable=True)

    # Auto-payout tracking (Phase 12)
    seller_wallet_address: Mapped[str] = mapped_column(String(256), nullable=True)
    payout_status: Mapped[str] = mapped_column(
        String(32), nullable=True
    )  # pending|sent|failed|manual
    payout_error: Mapped[str] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    product: Mapped[Product] = relationship("Product", back_populates="deals")


class ProductReview(Base):
    """Reviews left by buyers for sellers after successful deals."""

    __tablename__ = "product_reviews"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    deal_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("marketplace_deals.id"), nullable=False, unique=True
    )
    reviewer_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id"), nullable=False
    )
    seller_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.telegram_id"), nullable=False, index=True
    )

    rating: Mapped[int] = mapped_column(nullable=False)  # 1 to 5
    comment: Mapped[str] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
