"""add anti-fraud fields

Revision ID: 1d7012cf5860
Revises: 6733b7c2dddf
Create Date: 2026-05-21 11:42:17.596385
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d7012cf5860'
down_revision: Union[str, None] = '6733b7c2dddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_shadowbanned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('dispute_count_buyer', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('dispute_count_seller', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dispute_count_seller')
    op.drop_column('users', 'dispute_count_buyer')
    op.drop_column('users', 'is_shadowbanned')
    # ### end Alembic commands ###
