"""add_on_chain_escrow_to_orders

Revision ID: 4293063be26a
Revises: ed000d51edf5
Create Date: 2026-05-11 17:24:46.021173
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4293063be26a"
down_revision: str | None = "ed000d51edf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("escrow_wallet_address", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("escrow_wallet_private_key_enc", sa.String(length=512), nullable=True)
    )
    op.add_column("orders", sa.Column("on_chain_tx_hash", sa.String(length=255), nullable=True))
    op.add_column("orders", sa.Column("on_chain_status", sa.String(length=50), nullable=False))
    op.create_index(
        op.f("ix_orders_escrow_wallet_address"), "orders", ["escrow_wallet_address"], unique=False
    )
    op.create_index(
        op.f("ix_orders_on_chain_tx_hash"), "orders", ["on_chain_tx_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_on_chain_tx_hash"), table_name="orders")
    op.drop_index(op.f("ix_orders_escrow_wallet_address"), table_name="orders")
    op.drop_column("orders", "on_chain_status")
    op.drop_column("orders", "on_chain_tx_hash")
    op.drop_column("orders", "escrow_wallet_private_key_enc")
    op.drop_column("orders", "escrow_wallet_address")
    # ### end Alembic commands ###
