"""add_seller_id_to_marketplace_deals

Revision ID: 62c2515efea4
Revises: 889c15d33bc5
Create Date: 2026-05-14 11:51:29.645039
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "62c2515efea4"
down_revision: str | None = "889c15d33bc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("marketplace_deals", sa.Column("seller_id", sa.BigInteger(), nullable=False))
    op.create_index(
        op.f("ix_marketplace_deals_seller_id"), "marketplace_deals", ["seller_id"], unique=False
    )
    op.create_foreign_key(
        None, "marketplace_deals", "users", ["seller_id"], ["telegram_id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "marketplace_deals", type_="foreignkey")
    op.drop_index(op.f("ix_marketplace_deals_seller_id"), table_name="marketplace_deals")
    op.drop_column("marketplace_deals", "seller_id")
    # ### end Alembic commands ###
