"""add promo codes

Revision ID: 6733b7c2dddf
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 11:34:32.308250
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6733b7c2dddf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='promo_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_index(op.f('ix_promo_codes_seller_id'), 'promo_codes', ['seller_id'], unique=False)
    op.add_column('marketplace_deals', sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('marketplace_deals', sa.Column('promo_code_id', sa.BigInteger(), nullable=True))
    op.add_column('marketplace_deals', sa.Column('seller_wallet_address', sa.String(length=256), nullable=True))
    op.add_column('marketplace_deals', sa.Column('payout_status', sa.String(length=32), nullable=True))
    op.add_column('marketplace_deals', sa.Column('payout_error', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'marketplace_deals', 'promo_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')
    op.add_column('referral_rewards', sa.Column('deal_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'referral_rewards', 'marketplace_deals', ['deal_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('referral_balance', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False))
    op.add_column('users', sa.Column('is_verified_seller', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified_seller')
    op.drop_column('users', 'referral_balance')
    op.drop_constraint(None, 'referral_rewards', type_='foreignkey')
    op.drop_column('referral_rewards', 'deal_id')
    op.drop_constraint(None, 'marketplace_deals', type_='foreignkey')
    op.drop_column('marketplace_deals', 'payout_error')
    op.drop_column('marketplace_deals', 'payout_status')
    op.drop_column('marketplace_deals', 'seller_wallet_address')
    op.drop_column('marketplace_deals', 'promo_code_id')
    op.drop_column('marketplace_deals', 'original_amount')
    op.drop_index(op.f('ix_promo_codes_seller_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
