"""add_marketplace_products

Revision ID: 889c15d33bc5
Revises: b9d88aed8b4d
Create Date: 2026-05-14 10:39:41.295482
"""

from __future__ import annotations

from collections.abc import Sequence

revision: str = "889c15d33bc5"
down_revision: str | None = "b9d88aed8b4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
