"""add product promotion fields

Revision ID: 91e3ac3c7d34
Revises: 1d7012cf5860
Create Date: 2026-05-21 11:46:58.276573
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "91e3ac3c7d34"
down_revision: str | None = "1d7012cf5860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("is_promoted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "products", sa.Column("promoted_until", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "promoted_until")
    op.drop_column("products", "is_promoted")
    # ### end Alembic commands ###
