"""consolidated_state

Revision ID: d1e8ea476e1b
Revises: 9e3d29343bd6
Create Date: 2026-05-11 23:37:49.525974
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d1e8ea476e1b"
down_revision: str | None = "9e3d29343bd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_audit_logs_admin_id"), "admin_audit_logs", ["admin_id"], unique=False
    )
    op.create_table(
        "b2b_licenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("telegram_payment_charge_id", sa.String(length=255), nullable=True),
        sa.Column("branding", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("bot_token_encrypted", sa.String(length=512), nullable=True),
        sa.Column("spend_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spend_id"),
    )
    op.create_index(
        op.f("ix_b2b_licenses_telegram_payment_charge_id"),
        "b2b_licenses",
        ["telegram_payment_charge_id"],
        unique=True,
    )
    op.create_table(
        "ton_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_ton", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("memo", sa.String(length=64), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ton_invoices_memo"), "ton_invoices", ["memo"], unique=True)
    op.add_column("ads", sa.Column("chain", sa.String(length=50), nullable=True))
    op.add_column("orders", sa.Column("chain", sa.String(length=50), nullable=True))
    op.add_column(
        "orders", sa.Column("escrow_wallet_address", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("escrow_wallet_private_key_enc", sa.String(length=512), nullable=True)
    )
    op.add_column("orders", sa.Column("on_chain_tx_hash", sa.String(length=255), nullable=True))
    op.add_column("orders", sa.Column("on_chain_status", sa.String(length=50), nullable=False))
    op.add_column(
        "orders",
        sa.Column("on_chain_gas_buffer", sa.Numeric(precision=18, scale=8), nullable=False),
    )
    op.create_index(
        op.f("ix_orders_escrow_wallet_address"), "orders", ["escrow_wallet_address"], unique=False
    )
    op.create_index(
        op.f("ix_orders_on_chain_tx_hash"), "orders", ["on_chain_tx_hash"], unique=False
    )
    op.add_column(
        "users",
        sa.Column("default_fiat", sa.String(length=10), server_default="USD", nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notifications_enabled")
    op.drop_column("users", "default_fiat")
    op.drop_index(op.f("ix_orders_on_chain_tx_hash"), table_name="orders")
    op.drop_index(op.f("ix_orders_escrow_wallet_address"), table_name="orders")
    op.drop_column("orders", "on_chain_gas_buffer")
    op.drop_column("orders", "on_chain_status")
    op.drop_column("orders", "on_chain_tx_hash")
    op.drop_column("orders", "escrow_wallet_private_key_enc")
    op.drop_column("orders", "escrow_wallet_address")
    op.drop_column("orders", "chain")
    op.drop_column("ads", "chain")
    op.drop_index(op.f("ix_ton_invoices_memo"), table_name="ton_invoices")
    op.drop_table("ton_invoices")
    op.drop_index(op.f("ix_b2b_licenses_telegram_payment_charge_id"), table_name="b2b_licenses")
    op.drop_table("b2b_licenses")
    op.drop_index(op.f("ix_admin_audit_logs_admin_id"), table_name="admin_audit_logs")
    op.drop_table("admin_audit_logs")
    # ### end Alembic commands ###
