"""add_deal_id_to_chat

Revision ID: d82da554c000
Revises: b5fe4e0fcc5b
Create Date: 2026-05-14 12:56:48.453052
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d82da554c000"
down_revision: str | None = "b5fe4e0fcc5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_reviews",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.BigInteger(), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["marketplace_deals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.telegram_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id"),
    )
    op.create_index(
        op.f("ix_product_reviews_seller_id"), "product_reviews", ["seller_id"], unique=False
    )
    op.add_column("chat_messages", sa.Column("deal_id", sa.UUID(), nullable=True))
    op.alter_column("chat_messages", "order_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_chat_messages_deal_id"), "chat_messages", ["deal_id"], unique=False)
    op.create_foreign_key(
        None, "chat_messages", "marketplace_deals", ["deal_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "users", sa.Column("rating_sum", sa.BigInteger(), server_default="0", nullable=False)
    )
    op.add_column(
        "users", sa.Column("review_count", sa.BigInteger(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "review_count")
    op.drop_column("users", "rating_sum")
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.drop_index(op.f("ix_chat_messages_deal_id"), table_name="chat_messages")
    op.alter_column("chat_messages", "order_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("chat_messages", "deal_id")
    op.drop_index(op.f("ix_product_reviews_seller_id"), table_name="product_reviews")
    op.drop_table("product_reviews")
    # ### end Alembic commands ###
