"""add_b2b_licenses_and_ton_invoices

Revision ID: e4810f7ad583
Revises: 9e3d29343bd6
Create Date: 2026-05-11 12:31:16.820104

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4810f7ad583"
down_revision: str | None = "9e3d29343bd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "b2b_licenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("telegram_payment_charge_id", sa.String(length=255), nullable=True),
        sa.Column("branding", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("bot_token_encrypted", sa.String(length=512), nullable=True),
        sa.Column("spend_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spend_id"),
    )
    op.create_index(
        op.f("ix_b2b_licenses_telegram_payment_charge_id"),
        "b2b_licenses",
        ["telegram_payment_charge_id"],
        unique=True,
    )
    op.create_table(
        "ton_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_ton", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("memo", sa.String(length=64), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ton_invoices_memo"), "ton_invoices", ["memo"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ton_invoices_memo"), table_name="ton_invoices")
    op.drop_table("ton_invoices")
    op.drop_index(op.f("ix_b2b_licenses_telegram_payment_charge_id"), table_name="b2b_licenses")
    # op.drop_index(op.f('ix_b2b_licenses_spend_id'), table_name='b2b_licenses') # Not indexed
    op.drop_table("b2b_licenses")
    # ### end Alembic commands ###
