"""add_b2b_licenses_and_ton_invoices

Revision ID: e4810f7ad583
Revises: 9e3d29343bd6
Create Date: 2026-05-11 12:31:16.820104
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e4810f7ad583"
down_revision: str | None = "9e3d29343bd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("language_code", sa.String(length=10), server_default="en", nullable=False),
        sa.Column("referred_by_id", sa.BigInteger(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("total_trades", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("successful_trades", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("daily_volume_usdt", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("daily_volume_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("binance_api_key_enc", sa.String(length=512), nullable=True),
        sa.Column("binance_api_secret_enc", sa.String(length=512), nullable=True),
        sa.Column("okx_api_key_enc", sa.String(length=512), nullable=True),
        sa.Column("okx_api_secret_enc", sa.String(length=512), nullable=True),
        sa.Column("bybit_api_key_enc", sa.String(length=512), nullable=True),
        sa.Column("bybit_api_secret_enc", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "ads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("maker_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Enum("buy", "sell", name="adtype"), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("fiat", sa.String(length=10), nullable=False),
        sa.Column("price_type", sa.Enum("fixed", "floating", name="pricetype"), nullable=False),
        sa.Column("price_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("min_limit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("max_limit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("payment_method_ids", sa.String(length=255), nullable=False),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["maker_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "b2b_licenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("telegram_payment_charge_id", sa.String(length=255), nullable=True),
        sa.Column("branding", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("bot_token_encrypted", sa.String(length=512), nullable=True),
        sa.Column("spend_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spend_id"),
    )
    op.create_index(
        op.f("ix_b2b_licenses_telegram_payment_charge_id"),
        "b2b_licenses",
        ["telegram_payment_charge_id"],
        unique=True,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("maker_id", sa.BigInteger(), nullable=False),
        sa.Column("taker_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "order_type", sa.Enum("sell_crypto", "buy_crypto", name="order_type"), nullable=False
        ),
        sa.Column(
            "asset",
            sa.Enum("BTC", "TON", "USDT", "USDC", "ETH", name="supported_asset"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("fiat_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fiat_currency", sa.String(length=10), nullable=False),
        sa.Column("payment_method", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_funding",
                "active",
                "escrow_held",
                "completed",
                "dispute",
                "cancelled",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("fiat_confirmed", sa.Boolean(), nullable=False),
        sa.Column("invoice_id", sa.String(length=128), nullable=True),
        sa.Column("spend_id", sa.String(length=128), nullable=True),
        sa.Column("crypto_pay_payload", sa.Text(), nullable=True),
        sa.Column("payment_url", sa.Text(), nullable=True),
        sa.Column("fee_percent", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("fee_fixed", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("total_fee", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("dispute_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["maker_id"],
            ["users.telegram_id"],
        ),
        sa.ForeignKeyConstraint(
            ["taker_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id"),
        sa.UniqueConstraint("spend_id"),
    )
    op.create_index(op.f("ix_orders_maker_id"), "orders", ["maker_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_taker_id"), "orders", ["taker_id"], unique=False)
    op.create_table(
        "ton_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_ton", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("memo", sa.String(length=64), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ton_invoices_memo"), "ton_invoices", ["memo"], unique=True)
    op.create_table(
        "user_payment_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("account_name", sa.String(length=128), nullable=False),
        sa.Column("account_number", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["payment_method_id"], ["payment_methods.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_wallets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("chain", sa.Enum("ton", "evm", name="wallet_chain"), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("encrypted_private_key", sa.String(length=1024), nullable=False),
        sa.Column("encrypted_mnemonic", sa.String(length=2048), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index(op.f("ix_user_wallets_user_id"), "user_wallets", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("photo_file_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_order_id"), "chat_messages", ["order_id"], unique=False)
    op.create_table(
        "dispute_tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.BigInteger(), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["creator_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["moderator_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "referral_rewards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referred_user_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("is_positive", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("referral_rewards")
    op.drop_table("dispute_tickets")
    op.drop_index(op.f("ix_chat_messages_order_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_user_wallets_user_id"), table_name="user_wallets")
    op.drop_table("user_wallets")
    op.drop_table("user_payment_details")
    op.drop_index(op.f("ix_ton_invoices_memo"), table_name="ton_invoices")
    op.drop_table("ton_invoices")
    op.drop_index(op.f("ix_orders_taker_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_maker_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_b2b_licenses_telegram_payment_charge_id"), table_name="b2b_licenses")
    op.drop_table("b2b_licenses")
    op.drop_table("ads")
    op.drop_table("users")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
