"""marketplace_multichain

Revision ID: f90904ad1d60
Revises: d82da554c000
Create Date: 2026-05-14 13:05:38.343752
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f90904ad1d60"
down_revision: str | None = "d82da554c000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Expand wallet_chain ENUM to include new chains
    op.execute("ALTER TYPE wallet_chain ADD VALUE IF NOT EXISTS 'solana'")
    op.execute("ALTER TYPE wallet_chain ADD VALUE IF NOT EXISTS 'tron'")

    op.add_column(
        "marketplace_deals",
        sa.Column(
            "blockchain",
            sa.Enum("ton", "evm", "solana", "tron", name="wallet_chain"),
            nullable=True,
        ),
    )
    op.add_column("marketplace_deals", sa.Column("network", sa.String(length=20), nullable=True))
    op.add_column(
        "marketplace_deals",
        sa.Column("escrow_wallet_address", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "marketplace_deals",
        sa.Column("escrow_wallet_private_key_enc", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "marketplace_deals", sa.Column("buyer_wallet_address", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "marketplace_deals", sa.Column("tx_hash_deposit", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "marketplace_deals", sa.Column("tx_hash_release", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column(
            "crypto_chain",
            sa.Enum("ton", "evm", "solana", "tron", name="wallet_chain"),
            nullable=True,
        ),
    )
    op.add_column("products", sa.Column("crypto_network", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "crypto_network")
    op.drop_column("products", "crypto_chain")
    op.drop_column("marketplace_deals", "tx_hash_release")
    op.drop_column("marketplace_deals", "tx_hash_deposit")
    op.drop_column("marketplace_deals", "buyer_wallet_address")
    op.drop_column("marketplace_deals", "escrow_wallet_private_key_enc")
    op.drop_column("marketplace_deals", "escrow_wallet_address")
    op.drop_column("marketplace_deals", "network")
    op.drop_column("marketplace_deals", "blockchain")
    # ### end Alembic commands ###
