"""Web3 Wallet Providers.

Each provider implements :class:`WalletProvider` for a specific blockchain.

Implementations:
- :class:`EvmWalletProvider` — keygen (eth-account) + balance (web3.py AsyncWeb3)
- :class:`TonWalletProvider` — keygen (pytoniq-core) + balance (Toncenter REST)
"""

from __future__ import annotations

import abc
import asyncio
import secrets
from decimal import Decimal
from typing import Any, cast

import structlog

# Optional heavy dependencies - moved to top level for testability
try:
    from eth_account import Account
    from web3 import AsyncWeb3

    HAS_EVM = True
except ImportError:
    HAS_EVM = False

try:
    from pytoniq import WalletV4R2  # type: ignore[attr-defined]
    from pytoniq_core import Address  # type: ignore[attr-defined]

    HAS_TON = True
except ImportError:
    HAS_TON = False

try:
    from solana.keypair import Keypair as SolanaKeypair
    from solana.rpc.async_api import AsyncClient as SolanaClient
    from solders.pubkey import Pubkey

    HAS_SOLANA = True
except ImportError:
    HAS_SOLANA = False

try:
    from tronpy import AsyncTron
    from tronpy.keys import PrivateKey as TronPrivateKey

    HAS_TRON = True
except ImportError:
    HAS_TRON = False

log = structlog.get_logger(__name__)


# ── Abstract Base ──────────────────────────────────────────────────────────────


class WalletProvider(abc.ABC):
    """Abstract base class for all blockchain wallet providers.

    Implementations MUST be safe to call from async context.
    CPU-bound key generation MUST be offloaded to a thread pool.
    """

    @abc.abstractmethod
    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a new wallet keypair for *user_id*.

        Args:
            user_id: Telegram ID of the user (used for logging only).

        Returns:
            Dict with keys:
            - ``address`` (str): public wallet address
            - ``private_key`` (str): raw private key (hex or WIF)
            - ``mnemonic`` (str | None): BIP-39/TON mnemonic phrase if applicable
        """

    @abc.abstractmethod
    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Return on-chain balance of *asset* at *address*.

        Args:
            address: Wallet address.
            asset: Asset ticker, e.g. ``"USDT"``, ``"TON"``, ``"BNB"``.

        Returns:
            Confirmed balance as :class:`~decimal.Decimal`.
        """

    @abc.abstractmethod
    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and broadcast a transfer transaction.

        Args:
            private_key: Sender's private key (hex string).
            to_address: Recipient address.
            asset: Asset ticker.
            amount: Amount to send.
            memo: Optional comment / payload.

        Returns:
            Transaction hash (hex string).
        """

    @abc.abstractmethod
    async def estimate_fee(self, asset: str) -> Decimal:
        """Estimate the network fee (gas) required for a typical transfer.

        Args:
            asset: Asset ticker.

        Returns:
            Estimated fee in the NATIVE asset of the chain (e.g. TON or BNB).
        """


# ── EVM Provider ───────────────────────────────────────────────────────────────


def _generate_evm_account() -> dict[str, str]:
    """Generate a fresh EVM account synchronously.

    Uses ``eth_account.Account.create()`` with OS-level entropy.
    Called inside ``asyncio.to_thread`` to avoid blocking the event loop.

    Returns:
        Dict with ``address``, ``private_key``, and ``mnemonic`` (BIP-39).
    """
    if not HAS_EVM:
        raise ImportError("eth-account not installed")

    # Enable HD wallet (BIP-39 mnemonic) support
    Account.enable_unaudited_hdwallet_features()  # noqa: S401

    # Generate 256-bit entropy → 24-word mnemonic → deterministic keypair
    mnemonic = Account.create_with_mnemonic()[1]
    acct = Account.from_mnemonic(mnemonic)

    return {
        "address": acct.address,  # EIP-55 checksum address, e.g. 0xABCD…
        "private_key": acct.key.hex(),  # 64-char hex (without 0x) — consistent with eth-account
        "mnemonic": mnemonic,  # 24-word BIP-39 phrase
    }


class EvmWalletProvider(WalletProvider):
    """EVM-compatible wallet provider (Ethereum, BNB Chain, Polygon, etc.).

    Key generation uses ``eth-account`` library (pure Python, no RPC needed).
    Mnemonic entropy is generated by the OS via :func:`secrets` internals.

    Args:
        rpc_url: JSON-RPC endpoint for balance/transfer operations.
    """

    def __init__(self, rpc_url: str) -> None:
        self.rpc_url = rpc_url

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a real EVM keypair off-thread.

        Returns:
            ``address``, ``private_key``, ``mnemonic`` (24-word BIP-39).
        """
        wallet = await asyncio.to_thread(_generate_evm_account)
        log.info(
            "evm_wallet_generated",
            user_id=user_id,
            address=wallet["address"],
            step="EvmWalletProvider.generate_wallet",
        )
        return wallet

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch native or ERC-20/BEP-20 token balance via JSON-RPC.

        Supported assets:
        - ``"BNB"`` / ``"ETH"`` — native balance via ``eth_getBalance``
        - ``"USDT"`` — BEP-20 USDT on BSC (contract ``0x55d398326f99059fF775485246999027B3197955``)
        - ``"USDC"`` — BEP-20 USDC on BSC (contract ``0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d``)

        Args:
            address: EVM wallet address (0x…).
            asset: Asset ticker (case-insensitive).

        Returns:
            Balance as :class:`~decimal.Decimal`. Returns ``Decimal("0")`` on any RPC error.
        """
        if not HAS_EVM:
            return Decimal("0")

        # BEP-20 / ERC-20 contract addresses on BSC mainnet
        erc20_contracts: dict[str, str] = {
            "USDT": "0x55d398326f99059fF775485246999027B3197955",
            "USDC": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
            "BUSD": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56",
        }
        # Minimal ERC-20 ABI — only balanceOf needed
        erc20_abi = [
            {
                "constant": True,
                "inputs": [{"name": "_owner", "type": "address"}],
                "name": "balanceOf",
                "outputs": [{"name": "balance", "type": "uint256"}],
                "type": "function",
            }
        ]
        try:
            w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(self.rpc_url))
            asset_upper = asset.upper()

            if asset_upper in ("BNB", "ETH", "MATIC"):
                # Native coin balance
                raw = await w3.eth.get_balance(AsyncWeb3.to_checksum_address(address))
                balance = Decimal(str(AsyncWeb3.from_wei(raw, "ether")))
            elif asset_upper in erc20_contracts:
                contract_addr = erc20_contracts[asset_upper]
                contract = w3.eth.contract(
                    address=AsyncWeb3.to_checksum_address(contract_addr),
                    abi=erc20_abi,
                )
                raw = await contract.functions.balanceOf(
                    AsyncWeb3.to_checksum_address(address)
                ).call()
                # All listed tokens use 18 decimals
                balance = Decimal(raw) / Decimal(10**18)
            else:
                log.warning(
                    "evm_balance_unsupported_asset",
                    asset=asset,
                    address=address,
                    step="EvmWalletProvider.get_balance",
                )
                return Decimal("0")

            log.info(
                "evm_balance_fetched",
                address=address,
                asset=asset_upper,
                balance=str(balance),
                step="EvmWalletProvider.get_balance",
            )
            return balance

        except Exception as exc:
            log.warning(
                "evm_balance_error",
                address=address,
                asset=asset,
                error=str(exc),
                step="EvmWalletProvider.get_balance",
            )
            return Decimal("0")

    async def estimate_fee(self, asset: str) -> Decimal:
        """Estimate EVM network fee (gas) in native coin (BNB/ETH)."""
        if not HAS_EVM:
            return Decimal("0.001")  # Fallback

        try:
            w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(self.rpc_url))
            gas_price = await w3.eth.gas_price

            # Native transfer is exactly 21k gas.
            # ERC-20 is usually 45k-65k. We use 100k for safety buffer.
            asset_upper = asset.upper()
            gas_limit = 21000 if asset_upper in ("BNB", "ETH", "MATIC") else 100000

            fee_wei = gas_price * gas_limit
            return Decimal(str(AsyncWeb3.from_wei(fee_wei, "ether")))
        except Exception:
            return Decimal("0.001")

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and broadcast an EVM transaction.

        Supports native assets (BNB/ETH) and ERC-20 (USDT/USDC).
        Uses EIP-1559 if supported by the provider, otherwise falls back to legacy.
        """
        if not HAS_EVM:
            raise RuntimeError("web3.py or eth-account not installed")

        w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(self.rpc_url))
        sender_account = Account.from_key(private_key)
        sender_address = sender_account.address
        asset_upper = asset.upper()

        # BEP-20 / ERC-20 contract addresses (matched with get_balance)
        erc20_contracts: dict[str, str] = {
            "USDT": "0x55d398326f99059fF775485246999027B3197955",
            "USDC": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
        }

        nonce = await w3.eth.get_transaction_count(sender_address)
        chain_id = await w3.eth.chain_id

        # Base transaction parameters
        tx: dict[str, Any] = {
            "nonce": nonce,
            "chainId": chain_id,
            "from": sender_address,
        }

        # Try to use EIP-1559 fees
        try:
            fee_history = await w3.eth.fee_history(1, "latest", [25.0])
            base_fee = fee_history["baseFeePerGas"][-1]
            priority_fee = w3.to_wei(1, "gwei")  # Standard priority
            tx["maxFeePerGas"] = base_fee * 2 + priority_fee
            tx["maxPriorityFeePerGas"] = priority_fee
        except Exception:
            # Fallback to legacy gas price
            tx["gasPrice"] = await w3.eth.gas_price

        if asset_upper in ("BNB", "ETH", "MATIC"):
            # Native transfer
            tx["to"] = AsyncWeb3.to_checksum_address(to_address)
            tx["value"] = w3.to_wei(amount, "ether")
            tx["data"] = b""
            tx["gas"] = await w3.eth.estimate_gas(tx)  # type: ignore[arg-type]
        elif asset_upper in erc20_contracts:
            # ERC-20 transfer
            contract_addr = erc20_contracts[asset_upper]
            erc20_abi = [
                {
                    "constant": False,
                    "inputs": [
                        {"name": "_to", "type": "address"},
                        {"name": "_value", "type": "uint256"},
                    ],
                    "name": "transfer",
                    "outputs": [{"name": "success", "type": "bool"}],
                    "type": "function",
                }
            ]
            contract = w3.eth.contract(
                address=AsyncWeb3.to_checksum_address(contract_addr), abi=erc20_abi
            )
            # Encode data manually to avoid full ABI overhead
            tx["to"] = AsyncWeb3.to_checksum_address(contract_addr)
            tx["value"] = 0
            # Convert amount to units (18 decimals)
            units = int(amount * Decimal(10**18))
            tx["data"] = contract.functions.transfer(
                AsyncWeb3.to_checksum_address(to_address), units
            )._encode_transaction_data()
            tx["gas"] = await w3.eth.estimate_gas(tx)  # type: ignore[arg-type]
        else:
            raise ValueError(f"Unsupported EVM asset: {asset}")

        # Sign and broadcast
        signed_tx = sender_account.sign_transaction(tx)
        tx_hash = await w3.eth.send_raw_transaction(signed_tx.raw_transaction)

        log.info(
            "evm_transfer_broadcast",
            tx_hash=tx_hash.hex(),
            asset=asset_upper,
            amount=str(amount),
            to=to_address,
            step="EvmWalletProvider.transfer",
        )
        return tx_hash.hex()


# ── TON Provider ───────────────────────────────────────────────────────────────


def _generate_ton_account() -> dict[str, str]:
    """Generate a fresh TON wallet (v4R2) synchronously.

    Uses ``pytoniq_core`` for mnemonic + key derivation.
    Called inside ``asyncio.to_thread`` to avoid blocking the event loop.

    Returns:
        Dict with ``address`` (bounceable base64), ``private_key`` (hex), ``mnemonic``.
    """
    if not HAS_TON:
        raise ImportError("pytoniq not installed")

    from pytoniq_core.crypto.keys import (
        mnemonic_new,
        mnemonic_to_private_key,
    )

    # 24-word TON mnemonic (not BIP-39 standard — TON uses its own KDF)
    mnemonic_words = mnemonic_new(24)
    mnemonic_phrase = " ".join(mnemonic_words)

    # Derive Ed25519 keypair
    public_key, private_key = mnemonic_to_private_key(mnemonic_words)

    from pytoniq.contract.wallets.wallet import WALLET_V4_R2_CODE

    # subwallet id for mainnet V4R2 is 698983191
    wallet_id = 698983191 + 0  # 0 is workchain
    from pytoniq_core.tlb.account import StateInit
    from pytoniq_core.tlb.custom.wallet import WalletV4Data

    data = WalletV4Data(public_key=public_key, wallet_id=wallet_id, seqno=0).serialize()
    state_init = StateInit(code=WALLET_V4_R2_CODE, data=data).serialize()
    address_obj = Address((0, state_init.hash))
    address = address_obj.to_str(is_user_friendly=True, is_bounceable=False)

    return {
        "address": address,  # non-bounceable UQ… string
        "private_key": private_key.hex(),  # 64-byte Ed25519 private key hex
        "mnemonic": mnemonic_phrase,  # 24-word TON mnemonic
    }


class TonWalletProvider(WalletProvider):
    """TON wallet provider using ``pytoniq`` LiteClient.

    Key generation is fully offline.
    Network operations use the high-performance LiteClient (Project Rule 5).

    Args:
        is_testnet: Whether to use TON testnet config.
    """

    def __init__(self, is_testnet: bool = False) -> None:
        self.is_testnet = is_testnet
        self._client: Any = None

    async def _get_client(self) -> Any:
        """Lazy initialization of LiteClient."""
        if self._client is None:
            from pytoniq import LiteClient  # type: ignore[attr-defined]

            if self.is_testnet:
                self._client = await LiteClient.from_testnet_config(trust_level=2)
            else:
                self._client = await LiteClient.from_mainnet_config(trust_level=2)
            await self._client.connect()
        return self._client

    async def connect(self) -> None:
        """Connect to TON network."""
        await self._get_client()

    async def disconnect(self) -> None:
        """Close LiteClient connection if active."""
        if self._client:
            await self._client.close()
            self._client = None

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a real TON WalletV4R2 keypair off-thread.

        Returns:
            ``address`` (UQ…), ``private_key`` (hex), ``mnemonic`` (24 words).
        """
        try:
            wallet = await asyncio.to_thread(_generate_ton_account)
        except Exception as exc:  # pragma: no cover
            log.warning(
                "ton_keygen_failed_using_stub",
                error=str(exc),
                user_id=user_id,
                step="TonWalletProvider.generate_wallet",
            )
            # Graceful fallback so the bot doesn't crash if library is unavailable
            wallet = {
                "address": f"UQStubAddressForUser{user_id}",
                "private_key": secrets.token_hex(64),
                "mnemonic": " ".join(secrets.token_hex(4) for _ in range(24)),
            }

        log.info(
            "ton_wallet_generated",
            user_id=user_id,
            address=wallet["address"],
            step="TonWalletProvider.generate_wallet",
        )
        return wallet

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch TON native or jetton balance via LiteClient.

        Supported assets:
        - ``"TON"`` — native TON balance

        Args:
            address: TON wallet address (UQ… or EQ…).
            asset: Asset ticker. Currently only ``"TON"`` is supported.

        Returns:
            Balance as :class:`~decimal.Decimal`. Returns ``Decimal("0")`` on any error.
        """
        if asset.upper() != "TON":
            log.info(
                "ton_balance_unsupported_asset",
                asset=asset,
                step="TonWalletProvider.get_balance",
            )
            return Decimal("0")

        try:
            client = await self._get_client()
            acc = await client.get_account_state(address)
            balance = Decimal(acc.balance) / Decimal(10**9)

            log.info(
                "ton_balance_fetched",
                address=address,
                balance=str(balance),
                step="TonWalletProvider.get_balance",
            )
            return balance

        except Exception as exc:
            log.warning(
                "ton_balance_error",
                address=address,
                error=str(exc),
                step="TonWalletProvider.get_balance",
            )
            return Decimal("0")

    async def estimate_fee(self, asset: str) -> Decimal:
        """Estimate TON network fee (gas) in native TON.

        Currently assumes ~0.05 TON as a safe buffer for simple transfer.
        """
        # For simple native transfer, 0.01-0.02 is usually enough.
        # 0.05 gives a safe margin for storage fees if account is new.
        return Decimal("0.05")

    async def get_transactions(self, address: str, limit: int = 20) -> list[dict[str, Any]]:
        """Fetch recent transactions for a given TON address via LiteClient.

        Merged from providers/ton.py for consolidation.

        Args:
            address: TON address to scan.
            limit: Number of transactions to fetch.

        Returns:
            List of transaction details with hash, amount, and memo.
        """
        client = await self._get_client()
        txs = await client.get_transactions(address, count=limit)

        results = []
        for tx in txs:
            in_msg = tx.in_msg
            if not in_msg or not in_msg.info or in_msg.info.type != "int_msg":
                continue

            # Extract memo (comment)
            memo = ""
            if in_msg.body:
                try:
                    cell = in_msg.body
                    slice_ = cell.begin_parse()
                    if len(slice_) >= 32:
                        prefix = slice_.load_uint(32)
                        if prefix == 0:
                            memo = slice_.load_snake_string()
                except Exception:
                    pass

            results.append(
                {
                    "hash": tx.hash.hex(),
                    "amount_nanotons": int(in_msg.info.value),
                    "memo": memo,
                    "utime": tx.utime,
                }
            )

        return results

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and send a TON transfer using pytoniq LiteClient.

        Only supports native TON for now.
        """
        if asset.upper() != "TON":
            raise ValueError(f"Unsupported TON asset: {asset}")

        if not HAS_TON:
            raise RuntimeError("pytoniq library is not installed")

        try:
            # 1. Initialize wallet object from private key
            wallet = WalletV4R2.from_private_key(bytes.fromhex(private_key))

            # 2. Get current seqno from chain
            client = await self._get_client()
            seqno = await wallet.get_seqno(client)

            # 3. Create and broadcast the transfer
            # pytoniq transfer() method handles seqno and broadcasting
            await wallet.transfer(
                client=client,
                to_addr=to_address,
                amount=int(amount * Decimal(10**9)),
                body=memo if memo else "",
            )

            # Wait a bit for the transaction to be broadcasted (hash is derived from message)
            # In LiteClient, we can derive the hash from the message we sent
            # For simplicity, we return a success indicator or hash if available.
            # wallet.transfer doesn't return the hash directly in current pytoniq versions.
            # We calculate it:
            query = wallet.create_transfer_message(
                to_addr=to_address,
                amount=int(amount * Decimal(10**9)),
                seqno=seqno,
                payload=memo if memo else "",
            )
            tx_hash = query.message.hash.hex()

            log.info(
                "ton_transfer_broadcast",
                tx_hash=tx_hash,
                asset="TON",
                amount=str(amount),
                to=to_address,
                seqno=seqno,
                step="TonWalletProvider.transfer",
            )
            return cast(str, tx_hash)

        except Exception as exc:
            log.error(
                "ton_transfer_failed",
                error=str(exc),
                to=to_address,
                amount=str(amount),
                step="TonWalletProvider.transfer",
            )
            raise RuntimeError(f"TON transfer failed: {exc}") from exc


# ── Solana Provider ────────────────────────────────────────────────────────────


class SolanaWalletProvider(WalletProvider):
    """Solana wallet provider using ``solana-py``.

    Args:
        rpc_url: Solana JSON-RPC endpoint.
    """

    def __init__(self, rpc_url: str = "https://api.mainnet-beta.solana.com") -> None:
        self.rpc_url = rpc_url

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a fresh Solana keypair."""
        if not HAS_SOLANA:
            raise ImportError("solana-py not installed")

        kp = SolanaKeypair()
        return {
            "address": str(kp.public_key),
            "private_key": kp.secret_key.hex(),
            "mnemonic": None,  # solana-py doesn't expose mnemonic easily in older versions
        }

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch SOL or SPL token balance."""
        if not HAS_SOLANA:
            return Decimal("0")

        if asset.upper() != "SOL":
            # For now only SOL is supported in MVP
            return Decimal("0")

        try:
            async with SolanaClient(self.rpc_url) as client:
                # Type ignore: Pubkey vs PublicKey mismatch in older solana-py
                resp = await client.get_balance(Pubkey.from_string(address))  # type: ignore[arg-type]
                # solana-py 0.28 returns GetBalanceResp
                balance = Decimal(resp.value) / Decimal(10**9)
                return balance
        except Exception as exc:
            log.warning("solana_balance_error", address=address, error=str(exc))
            return Decimal("0")

    async def estimate_fee(self, asset: str) -> Decimal:
        """Solana fee is usually fixed at 5000 lamports."""
        return Decimal("0.000005")

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and send SOL."""
        if not HAS_SOLANA:
            raise RuntimeError("solana-py not installed")

        if asset.upper() != "SOL":
            raise ValueError(f"Unsupported Solana asset: {asset}")

        from solana.system_program import TransferParams, transfer
        from solana.transaction import Transaction

        sender_kp = SolanaKeypair.from_secret_key(bytes.fromhex(private_key))
        to_pubkey = Pubkey.from_string(to_address)
        lamports = int(amount * Decimal(10**9))

        async with SolanaClient(self.rpc_url) as client:
            # 1. Get recent blockhash
            recent_blockhash_resp = await client.get_latest_blockhash()
            recent_blockhash = recent_blockhash_resp.value.blockhash

            # 2. Build transaction
            txn = Transaction(recent_blockhash=recent_blockhash)  # type: ignore[arg-type]
            txn.add(
                transfer(
                    TransferParams(
                        from_pubkey=sender_kp.public_key,
                        to_pubkey=to_pubkey,  # type: ignore[arg-type]
                        lamports=lamports,
                    )
                )
            )

            # 3. Sign and send
            resp = await client.send_transaction(txn, sender_kp)
            tx_hash = str(resp.value)

            log.info(
                "solana_transfer_broadcast",
                tx_hash=tx_hash,
                to=to_address,
                amount=str(amount),
            )
            return tx_hash


# ── Tron Provider ──────────────────────────────────────────────────────────────


class TronWalletProvider(WalletProvider):
    """Tron wallet provider using ``tronpy``.

    Args:
        is_mainnet: Whether to use Tron mainnet or Nile testnet.
    """

    def __init__(self, is_mainnet: bool = True) -> None:
        self.network = "mainnet" if is_mainnet else "nile"

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a fresh Tron keypair."""
        if not HAS_TRON:
            raise ImportError("tronpy not installed")

        # Tronpy keygen is fast enough for event loop but we follow the pattern
        def _gen() -> dict[str, Any]:
            from tronpy.keys import PrivateKey

            pk = PrivateKey.random()
            return {
                "address": pk.public_key.to_base58check_address(),
                "private_key": pk.hex(),
                "mnemonic": None,
            }

        return await asyncio.to_thread(_gen)

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch TRX or TRC-20 balance."""
        if not HAS_TRON:
            return Decimal("0")

        try:
            async with AsyncTron(network=self.network) as client:
                if asset.upper() == "TRX":
                    balance = await client.get_account_balance(address)
                    return Decimal(str(balance))
                else:
                    # TRC-20 USDT/USDC (simplified)
                    contracts = {
                        "USDT": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
                        "USDC": "TE7EE4GEPhCDS9iK1S8YQd9wG877Y379mK",
                    }
                    if asset.upper() in contracts:
                        cntr = await client.get_contract(contracts[asset.upper()])
                        raw = await cntr.functions.balanceOf(address)
                        return Decimal(str(raw)) / Decimal(10**6)
                    return Decimal("0")
        except Exception as exc:
            log.warning("tron_balance_error", address=address, error=str(exc))
            return Decimal("0")

    async def estimate_fee(self, asset: str) -> Decimal:
        """Tron fee is usually 1-2 TRX for native, 13-30 TRX for TRC-20."""
        return Decimal("1.0") if asset.upper() == "TRX" else Decimal("15.0")

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and send TRX or TRC-20."""
        if not HAS_TRON:
            raise RuntimeError("tronpy not installed")

        async with AsyncTron(network=self.network) as client:
            priv_key = TronPrivateKey(bytes.fromhex(private_key))
            if asset.upper() == "TRX":
                from_addr = priv_key.public_key.to_base58check_address()
                sun_amount = int(amount * 1_000_000)
                txn = (
                    client.trx.transfer(from_addr, to_address, sun_amount)
                    .memo(memo or "")
                    .build()
                    .sign(priv_key)
                )
                result = await txn.broadcast()
                tx_hash = result["txid"]
            else:
                # TRC-20 Transfer
                contracts = {
                    "USDT": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
                }
                if asset.upper() not in contracts:
                    raise ValueError(f"Unsupported Tron asset: {asset}")

                cntr = await client.get_contract(contracts[asset.upper()])
                txn = (
                    cntr.functions.transfer(to_address, int(amount * 1_000_000))
                    .with_owner(priv_key.public_key.to_base58check_address())
                    .memo(memo or "")
                    .build()
                    .sign(priv_key)
                )
                result = await txn.broadcast()
                tx_hash = result["txid"]

            log.info(
                "tron_transfer_broadcast",
                tx_hash=tx_hash,
                to=to_address,
                amount=str(amount),
            )
            return str(tx_hash)
