"""Web3 Wallet Providers.

Each provider implements :class:`WalletProvider` for a specific blockchain.

Implementations:
- :class:`EvmWalletProvider` — keygen (eth-account) + balance (web3.py AsyncWeb3)
- :class:`TonWalletProvider` — keygen (pytoniq-core) + balance (Toncenter REST)

Transfer methods are stubs pending Phase 5.
"""

from __future__ import annotations

import abc
import asyncio
import secrets
from decimal import Decimal
from typing import Any

import structlog

log = structlog.get_logger(__name__)


# ── Abstract Base ──────────────────────────────────────────────────────────────


class WalletProvider(abc.ABC):
    """Abstract base class for all blockchain wallet providers.

    Implementations MUST be safe to call from async context.
    CPU-bound key generation MUST be offloaded to a thread pool.
    """

    @abc.abstractmethod
    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a new wallet keypair for *user_id*.

        Args:
            user_id: Telegram ID of the user (used for logging only).

        Returns:
            Dict with keys:
            - ``address`` (str): public wallet address
            - ``private_key`` (str): raw private key (hex or WIF)
            - ``mnemonic`` (str | None): BIP-39/TON mnemonic phrase if applicable
        """

    @abc.abstractmethod
    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Return on-chain balance of *asset* at *address*.

        Args:
            address: Wallet address.
            asset: Asset ticker, e.g. ``"USDT"``, ``"TON"``, ``"BNB"``.

        Returns:
            Confirmed balance as :class:`~decimal.Decimal`.
        """

    @abc.abstractmethod
    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and broadcast a transfer transaction.

        Args:
            private_key: Sender's private key (hex string).
            to_address: Recipient address.
            asset: Asset ticker.
            amount: Amount to send.
            memo: Optional comment / payload.

        Returns:
            Transaction hash (hex string).
        """


# ── EVM Provider ───────────────────────────────────────────────────────────────


def _generate_evm_account() -> dict[str, str]:
    """Generate a fresh EVM account synchronously.

    Uses ``eth_account.Account.create()`` with OS-level entropy.
    Called inside ``asyncio.to_thread`` to avoid blocking the event loop.

    Returns:
        Dict with ``address``, ``private_key``, and ``mnemonic`` (BIP-39).
    """
    from eth_account import Account

    # Enable HD wallet (BIP-39 mnemonic) support
    Account.enable_unaudited_hdwallet_features()

    # Generate 256-bit entropy → 24-word mnemonic → deterministic keypair
    mnemonic = Account.create_with_mnemonic()[1]
    acct = Account.from_mnemonic(mnemonic)

    return {
        "address": acct.address,  # EIP-55 checksum address, e.g. 0xABCD…
        "private_key": acct.key.hex(),  # 64-char hex (without 0x) — consistent with eth-account
        "mnemonic": mnemonic,  # 24-word BIP-39 phrase
    }


class EvmWalletProvider(WalletProvider):
    """EVM-compatible wallet provider (Ethereum, BNB Chain, Polygon, etc.).

    Key generation uses ``eth-account`` library (pure Python, no RPC needed).
    Mnemonic entropy is generated by the OS via :func:`secrets` internals.

    Args:
        rpc_url: JSON-RPC endpoint for balance/transfer operations.
    """

    def __init__(self, rpc_url: str) -> None:
        self.rpc_url = rpc_url

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a real EVM keypair off-thread.

        Returns:
            ``address``, ``private_key``, ``mnemonic`` (24-word BIP-39).
        """
        wallet = await asyncio.to_thread(_generate_evm_account)
        log.info(
            "evm_wallet_generated",
            user_id=user_id,
            address=wallet["address"],
            step="EvmWalletProvider.generate_wallet",
        )
        return wallet

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch native or ERC-20/BEP-20 token balance via JSON-RPC.

        Supported assets:
        - ``"BNB"`` / ``"ETH"`` — native balance via ``eth_getBalance``
        - ``"USDT"`` — BEP-20 USDT on BSC (contract ``0x55d398326f99059fF775485246999027B3197955``)
        - ``"USDC"`` — BEP-20 USDC on BSC (contract ``0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d``)

        Args:
            address: EVM wallet address (0x…).
            asset: Asset ticker (case-insensitive).

        Returns:
            Balance as :class:`~decimal.Decimal`. Returns ``Decimal("0")`` on any RPC error.
        """
        # BEP-20 / ERC-20 contract addresses on BSC mainnet
        erc20_contracts: dict[str, str] = {
            "USDT": "0x55d398326f99059fF775485246999027B3197955",
            "USDC": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
            "BUSD": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56",
        }
        # Minimal ERC-20 ABI — only balanceOf needed
        erc20_abi = [
            {
                "constant": True,
                "inputs": [{"name": "_owner", "type": "address"}],
                "name": "balanceOf",
                "outputs": [{"name": "balance", "type": "uint256"}],
                "type": "function",
            }
        ]
        try:
            from web3 import AsyncWeb3

            w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(self.rpc_url))
            asset_upper = asset.upper()

            if asset_upper in ("BNB", "ETH", "MATIC"):
                # Native coin balance
                raw = await w3.eth.get_balance(AsyncWeb3.to_checksum_address(address))
                balance = Decimal(str(AsyncWeb3.from_wei(raw, "ether")))
            elif asset_upper in erc20_contracts:
                contract_addr = erc20_contracts[asset_upper]
                contract = w3.eth.contract(
                    address=AsyncWeb3.to_checksum_address(contract_addr),
                    abi=erc20_abi,
                )
                raw = await contract.functions.balanceOf(
                    AsyncWeb3.to_checksum_address(address)
                ).call()
                # All listed tokens use 18 decimals
                balance = Decimal(raw) / Decimal(10**18)
            else:
                log.warning(
                    "evm_balance_unsupported_asset",
                    asset=asset,
                    address=address,
                    step="EvmWalletProvider.get_balance",
                )
                return Decimal("0")

            log.info(
                "evm_balance_fetched",
                address=address,
                asset=asset_upper,
                balance=str(balance),
                step="EvmWalletProvider.get_balance",
            )
            return balance

        except Exception as exc:
            log.warning(
                "evm_balance_error",
                address=address,
                asset=asset,
                error=str(exc),
                step="EvmWalletProvider.get_balance",
            )
            return Decimal("0")

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and broadcast an EVM transaction. (Phase 4 — not yet implemented.)"""
        log.info(
            "evm_transfer_stub",
            to_address=to_address,
            asset=asset,
            amount=str(amount),
            step="EvmWalletProvider.transfer",
        )
        # TODO Phase 4: build raw tx, sign with eth_account, send via eth_sendRawTransaction
        return "0x" + secrets.token_hex(32)  # nosec B311


# ── TON Provider ───────────────────────────────────────────────────────────────


def _generate_ton_account() -> dict[str, str]:
    """Generate a fresh TON wallet (v4R2) synchronously.

    Uses ``pytoniq_core`` for mnemonic + key derivation.
    Called inside ``asyncio.to_thread`` to avoid blocking the event loop.

    Returns:
        Dict with ``address`` (bounceable base64), ``private_key`` (hex), ``mnemonic``.
    """
    from pytoniq_core.crypto.keys import (
        mnemonic_new,
        mnemonic_to_private_key,
    )

    # 24-word TON mnemonic (not BIP-39 standard — TON uses its own KDF)
    mnemonic_words = mnemonic_new(24)
    mnemonic_phrase = " ".join(mnemonic_words)

    # Derive Ed25519 keypair
    public_key, private_key = mnemonic_to_private_key(mnemonic_words)

    # Derive WalletV4R2 address on mainnet (workchain 0)
    from pytoniq_core.contract.wallets import WalletV4R2

    wallet = WalletV4R2.create(public_key=public_key)
    address = wallet.address.to_str(is_user_friendly=True, is_bounceable=False)

    return {
        "address": address,  # non-bounceable UQ… string
        "private_key": private_key.hex(),  # 64-byte Ed25519 private key hex
        "mnemonic": mnemonic_phrase,  # 24-word TON mnemonic
    }


class TonWalletProvider(WalletProvider):
    """TON wallet provider using ``pytoniq-core``.

    Key generation is fully offline — no network call required.

    Args:
        endpoint: Toncenter or LiteServer JSON-RPC URL.
        api_key: Optional Toncenter API key for higher rate limits.
    """

    def __init__(self, endpoint: str, api_key: str | None = None) -> None:
        self.endpoint = endpoint
        self.api_key = api_key

    async def generate_wallet(self, user_id: int) -> dict[str, Any]:
        """Generate a real TON WalletV4R2 keypair off-thread.

        Returns:
            ``address`` (UQ…), ``private_key`` (hex), ``mnemonic`` (24 words).
        """
        try:
            wallet = await asyncio.to_thread(_generate_ton_account)
        except Exception as exc:  # pragma: no cover
            log.warning(
                "ton_keygen_failed_using_stub",
                error=str(exc),
                user_id=user_id,
                step="TonWalletProvider.generate_wallet",
            )
            # Graceful fallback so the bot doesn't crash if library is unavailable
            wallet = {
                "address": f"UQStubAddressForUser{user_id}",
                "private_key": secrets.token_hex(64),  # nosec B311
                "mnemonic": " ".join(secrets.token_hex(4) for _ in range(24)),  # nosec B311
            }

        log.info(
            "ton_wallet_generated",
            user_id=user_id,
            address=wallet["address"],
            step="TonWalletProvider.generate_wallet",
        )
        return wallet

    async def get_balance(self, address: str, asset: str) -> Decimal:
        """Fetch TON native or jetton balance via Toncenter v2 REST API.

        Supported assets:
        - ``"TON"`` — native TON balance
        - Jetton balances are planned for Phase 5

        Args:
            address: TON wallet address (UQ… or EQ…).
            asset: Asset ticker. Currently only ``"TON"`` is supported.

        Returns:
            Balance as :class:`~decimal.Decimal`. Returns ``Decimal("0")`` on any error.
        """
        if asset.upper() != "TON":
            log.info(
                "ton_balance_unsupported_asset",
                asset=asset,
                step="TonWalletProvider.get_balance",
            )
            return Decimal("0")

        try:
            import aiohttp  # already in requirements

            params = {"address": address}
            headers = {}
            if self.api_key:
                headers["X-API-Key"] = self.api_key

            url = self.endpoint.rstrip("/").replace("/jsonRPC", "") + "/getAddressBalance"

            async with (
                aiohttp.ClientSession(headers=headers) as http,
                http.get(url, params=params, timeout=aiohttp.ClientTimeout(total=10)) as resp,
            ):
                if resp.status != 200:
                    log.warning(
                        "ton_balance_http_error",
                        status=resp.status,
                        address=address,
                        step="TonWalletProvider.get_balance",
                    )
                    return Decimal("0")
                data = await resp.json()

            if not data.get("ok"):
                return Decimal("0")

            # Balance is in nanotons (1 TON = 1e9 nanotons)
            nanotons = int(data["result"])
            balance = Decimal(nanotons) / Decimal(10**9)

            log.info(
                "ton_balance_fetched",
                address=address,
                balance=str(balance),
                step="TonWalletProvider.get_balance",
            )
            return balance

        except Exception as exc:
            log.warning(
                "ton_balance_error",
                address=address,
                error=str(exc),
                step="TonWalletProvider.get_balance",
            )
            return Decimal("0")

    async def transfer(
        self,
        private_key: str,
        to_address: str,
        asset: str,
        amount: Decimal,
        memo: str | None = None,
    ) -> str:
        """Sign and send a TON transfer. (Phase 4 — not yet implemented.)"""
        log.info(
            "ton_transfer_stub",
            to_address=to_address,
            asset=asset,
            amount=str(amount),
            step="TonWalletProvider.transfer",
        )
        # TODO Phase 4: build TON transfer BoC, sign, publish via Toncenter sendBoc
        return secrets.token_hex(32)  # nosec B311
